[run]
dimension=2
tEnd=3.0
nStepmax=6000
nlog=100

# noutput equals -1 means we dump data at every time steps
nOutput=10

[amr]
level_min=2
level_max=5

use_block_data=yes
bx=4
by=4

# amr refine criterion use at init condition
# possible value: ALWAYS_REFINE, GEOMETRIC, SAME_AS_REGULAR_DYNAMICS
refine_criterion_at_init=GEOMETRIC

# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# refine criterion (used during regular dynamics)
# example parameter for using LOHNER_UNSPLIT criterion
refine_criterion=LOHNER_UNSPLIT
epsilon_refine=0.08
epsilon_coarsen=0.01
epsilon_lohner=0.02

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=SIMPLE_GRADIENT
#epsilon_refine=0.1
#epsilon_coarsen=0.01

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=10

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=5

[p4est_connectivity]
nbrick_x=1
nbrick_y=1

periodic_x=1
periodic_y=1

[mesh]
xmin=0.0
ymin=0.0

scaling_factor=1.0

boundary_type_xmin=WALL
boundary_type_xmax=WALL

boundary_type_ymin=WALL
boundary_type_ymax=WALL

[hydro]
gamma0=1.666
cfl=0.8
niter_riemann=10
slope_type=2
problem=kelvin_helmholtz
riemann=HLLD
implementation_version=0

[viscosity]
enabled=no
mu=0.0001

[kelvin_helmholtz]
#
# see http://www.astro.princeton.edu/~jstone/Athena/tests/kh/kh.html
#

# amplitude of interface initial perturbation
amplitude = 0.01

# perturbation type (0 to deactivate, 1 to activate)
perturbation_sine = 0
perturbation_sine_robertson = 1
perturbation_rand = 0

# single mode perturbation a la Robertson
mode = 2
w0 = 0.1
delta = 0.005

# random seed (only used when perturbation_type is random)
# each MPI process get initialized with srand(seed*(mpiRank+1))
rand_seed = 131

# density of the fluids
d_in = 2.0
d_out = 1.0

# half thickness of the two domain.
# inner_size must be smaller than outer_size.
inner_size = 0.25
outer_size = 0.25

# pressure
pressure = 2.5

# magnetic field
bx=0.1
by=0.0
bz=0.0

[output]
outputDir=./
outputPrefix=test_mhd_kelvin_helmholtz_2d
outputVtkAscii=false
write_variables=Bx,By,Bz,rho,rho_vx,rho_vy,e_tot,divB
write_mesh_info=yes
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no
